// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727192652_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("catOrder")
                        .HasColumnType("int");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id");

                    b.ToTable("Categories", "MasterSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            catName = "Fiction",
                            catOrder = 1,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            catName = "Science",
                            catOrder = 2,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            catName = "History",
                            catOrder = 3,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            catName = "Technology",
                            catOrder = 4,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            catName = "Philosophy",
                            catOrder = 5,
                            markedAsDeleted = false
                        });
                });

            modelBuilder.Entity("Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("BookPrice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "MasterSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            CategoryId = 1,
                            Description = "Dystopian novel",
                            Price = 49.990000000000002,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andy Weir",
                            CategoryId = 2,
                            Description = "Sci-fi survival story",
                            Price = 59.990000000000002,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Aldous Huxley",
                            CategoryId = 1,
                            Description = "Classic dystopia",
                            Price = 39.990000000000002,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            CategoryId = 3,
                            Description = "A brief history of humankind",
                            Price = 64.989999999999995,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert C. Martin",
                            CategoryId = 4,
                            Description = "Best practices for writing clean code",
                            Price = 74.989999999999995,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Marcus Aurelius",
                            CategoryId = 5,
                            Description = "Thoughts of Marcus Aurelius",
                            Price = 29.989999999999998,
                            Title = "Meditations"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Neil deGrasse Tyson",
                            CategoryId = 2,
                            Description = "Science made simple",
                            Price = 41.990000000000002,
                            Title = "Astrophysics for People in a Hurry"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Richard Dawkins",
                            CategoryId = 2,
                            Description = "Evolution explained",
                            Price = 52.990000000000002,
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Sun Tzu",
                            CategoryId = 3,
                            Description = "Classic Chinese military treatise",
                            Price = 24.989999999999998,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Plato",
                            CategoryId = 5,
                            Description = "Philosophical dialogue by Plato",
                            Price = 34.990000000000002,
                            Title = "The Republic"
                        });
                });

            modelBuilder.Entity("Models.Entities.Product", b =>
                {
                    b.HasOne("Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
